eureka:
  client:
    service-url:
      default-zone: http://EUREKA-SERVER
  
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/MohammedRinish25/Watermark-Templates
   
  application:
    name: CONFIG-SERVER